version: '3.9'
services:
  hgu_ssb_club_bot:
    build: .
    image: python:3.9-slim
    container_name: hgu_ssb_club_bot
    working_dir: /app
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: python /app/main.py
    restart: always
