name: Docker image CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: Deploy to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            cd /home/atamol/HU_SSB_Club_Bot
            docker-compose down || true
            docker rm -f HU_SSB_Club_Bot || true
            docker image rm -f HU_SSB_Club_Bot:latest || true
            git pull origin main
            docker-compose up -d --build
            echo "Deployment Complete"
          EOF
