name: Docker image CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
    - self-hosted

    steps:
      - name: Configure Git Safe Directory
        run: |
          export HOME=/home/actions-runner/Runner-HGU_SSB_Club_Bot
          git config --global --add safe.directory /home/actions-runner/Runner-HGU_SSB_Club_Bot/_work/HGU_SSB_Club_Bot/HGU_SSB_Club_Bot

      - name: Check out repository
        uses: actions/checkout@v3

      - name: create env file
        run: |
          touch .env
          echo DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} >> .env
          echo DISCORD_BUTTON_CHANNEL_ID=${{ secrets.DISCORD_BUTTON_CHANNEL_ID }} >> .env
          echo DISCORD_LOG_CHANNEL_ID=${{ secrets.DISCORD_LOG_CHANNEL_ID }} >> .env

      - name: Stop Existing Docker Containers
        run: docker-compose down || true

      - name: Remove Old Docker Container
        run: docker rm -f hgu_ssb_club_bot || true

      - name: Remove Old Docker Image
        run: docker image rm -f hgu_ssb_club_bot:latest || true

      - name: Pull Latest Changes from Repository
        run: git pull origin main

      - name: Build and Start Docker Container
        run: docker-compose up -d --build
